---
galaxy_info:
  author: Daniel Peyer
  description: Manage common workstation packages and package repository settings.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
