---
desktop_suckless_recommended_font_packages:
  - nerd-fonts
  - noto-emoji
  - font-awesome
  - terminus-font
  - inconsolata-ttf

suckless_flexipatch_packages:
  - bash
  - git
  - gmake
  - pkgconf
  - libX11
  - libXft
  - libXinerama
  - fontconfig
  - freetype2

suckless_flexipatch_source_root: /usr/local/src

suckless_flexipatch_owner: root
suckless_flexipatch_group: wheel

suckless_flexipatch_git_update: true
suckless_flexipatch_git_force: false

suckless_flexipatch_recreate_final_directories: true
suckless_flexipatch_make_command: /usr/local/bin/gmake
suckless_flexipatch_make_environment:
  PREFIX: /usr/local

flexipatch_items: []
flexipatch_finalizer: {}

#desktop_suckless_git_user: root
#desktop_suckless_git_group: wheel
#
#desktop_suckless_git_ssh_directory: /root/.ssh
#desktop_suckless_git_private_key: /root/.ssh/id_ed25519
#desktop_suckless_git_known_hosts: /root/.ssh/known_hosts
#
#desktop_suckless_git_accept_hostkey: true
#desktop_suckless_git_manage_key_permissions: true
#
#desktop_suckless_git_known_hosts_entries: []