---
desktop_suckless_recommended_font_packages:
  - nerd-fonts
  - noto-emoji
  - font-awesome
  - terminus-font
  - inconsolata-ttf

suckless_flexipatch_packages:
  - bash
  - git
  - gmake
  - pkgconf
  - libX11
  - libXft
  - libXinerama
  - fontconfig
  - freetype2

suckless_flexipatch_source_root: /usr/local/src

suckless_flexipatch_owner: root
suckless_flexipatch_group: wheel

suckless_flexipatch_git_update: true
suckless_flexipatch_git_force: false

suckless_flexipatch_recreate_final_directories: true
suckless_make_command: /usr/local/bin/gmake
suckless_flexipatch_make_environment:
  PREFIX: /usr/local

# Suckless desktop repositories.
suckless_items:
  - name: dwm
    repo: git@github.com:lirux9873/dwm-flexipatch.git
    src: /usr/local/src/dwm-flexipatch
    final: /usr/local/src/dwm-final
    version: master
    enabled: true
    make_args: []
    install_args: []

  - name: dmenu
    repo: git@github.com:lirux9873/dmenu-flexipatch.git
    src: /usr/local/src/dmenu-flexipatch
    final: /usr/local/src/dmenu-final
    version: master
    enabled: true
    make_args: []
    install_args: []

  - name: st
    repo: git@github.com:lirux9873/st-flexipatch.git
    src: /usr/local/src/st-flexipatch
    final: /usr/local/src/st-final
    version: master
    enabled: true
    make_args: []
    install_args: []

flexipatch_finalizer:
  name: flexipatch-finalizer
  repo: git@github.com:lirux9873/flexipatch-finalizer.git
  src: /usr/local/src/flexipatch-finalizer
  version: master
  script: /usr/local/src/flexipatch-finalizer/flexipatch-finalizer_freebsd.sh

desktop_suckless_git_user: daniel   # root
desktop_suckless_git_group: daniel  # wheel

desktop_suckless_git_ssh_directory: /home/daniel/.ssh
desktop_suckless_git_private_key: /home/daniel/.ssh/id_ed25519
desktop_suckless_git_known_hosts: /home/daniel/.ssh/known_hosts

desktop_suckless_git_accept_hostkey: true
desktop_suckless_git_manage_key_permissions: true

desktop_suckless_git_known_hosts_entries: []