---
- name: Bootstrap Ansible collection dependencies
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

- name: Configure FreeBSD workstation
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars/profile_suckless.yml

  roles:
    - c9.freebsd_workstation.common_validation
    - c9.freebsd_workstation.common_packages
    - c9.freebsd_workstation.common_users
    - c9.freebsd_workstation.common_sudo
    - c9.freebsd_workstation.common_localization
    - c9.freebsd_workstation.common_fonts
    - c9.freebsd_workstation.service_ntpsec
    - c9.freebsd_workstation.service_ssh
    - c9.freebsd_workstation.networking_base
    - c9.freebsd_workstation.security_base
    - c9.freebsd_workstation.desktop_common
    - c9.freebsd_workstation.desktop_xorg
    - c9.freebsd_workstation.desktop_suckless
    - c9.freebsd_workstation.validation_workstation
