---
- name: Configure FreeBSD Sway workstation
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars/profile_sway.yml

  roles:
    - c9.freebsd_workstation.common_validation
    - c9.freebsd_workstation.common_packages
    - c9.freebsd_workstation.common_users
    - c9.freebsd_workstation.common_sudo
    - c9.freebsd_workstation.common_localization
    - c9.freebsd_workstation.common_fonts
    - c9.freebsd_workstation.service_dbus
    - c9.freebsd_workstation.service_seatd
    - c9.freebsd_workstation.service_ntpsec
    - c9.freebsd_workstation.networking_base
    - c9.freebsd_workstation.security_base
    - c9.freebsd_workstation.desktop_common
    - c9.freebsd_workstation.desktop_wayland
    - c9.freebsd_workstation.desktop_sway
    - c9.freebsd_workstation.validation_workstation
