---
galaxy_info:
  author: Daniel Peyer
  description: Install and configure OpenSSH services and client defaults.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
