---
galaxy_info:
  author: Daniel Peyer
  description: Manage shared directories, permissions, and filesystem conventions.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
