---
galaxy_info:
  author: Daniel Peyer
  description: Clone, finalize, build, and install dwm, dmenu, and st on FreeBSD
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
