---
galaxy_info:
  author: Daniel Peyer
  description: Configure locale, timezone, keyboard, and regional settings.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
