---
galaxy_info:
  author: Daniel Peyer
  description: Install desktop-wide utilities shared by all desktop profiles.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies: []
