---
galaxy_info:
  author: Daniel Peyer
  description: Install system-wide fonts on FreeBSD
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: FreeBSD
      versions:
        - all

dependencies: []
