---
- name: Clean and build Suckless applications
  community.general.make:
    chdir: "{{ item.src }}"
    target: dist
    make: gmake
  loop: "{{ suckless_items }}"
  loop_control:
    label: "{{ item.name }}: gmake"
  when: item.enabled | default(true) | bool
  changed_when: true