---
- name: Install Suckless applications
  community.general.make:
    chdir: "{{ item.final }}"
    target: install
    make: gmake
  loop: "{{ suckless_items }}"
  loop_control:
    label: "Install {{ item.name }} with gmake install"
  when: item.enabled | default(true) | bool
  changed_when: true